queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=DCO
      - check-success=docker-images
      - check-success=validation

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
      - check-success=DCO
      - check-success=docker-images
      - check-success=validation
      - label!=do-not-merge
      - label=ready-to-merge
    actions:
      queue:
        method: merge
        name: default
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}
