---

workspace:
  base: /go
  path: src/github.com/packethost/tinkerbell

pipeline:
  build:
    group: ci
    image: golang:1.13-alpine
    commands:
      - CGO_ENABLED=0 go build

  test:
    group: ci
    image: golang:1.13-alpine
    commands:
      - go test -v ./test/

