proto_outdir = "./protos/third_party"

[[dependencies]]
  target = "github.com/protocolbuffers/protobuf/src/google/protobuf/timestamp.proto"
  revision = "v3.13.0"
  path = "google/protobuf/timestamp.proto"

[[dependencies]]
  target = "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google"
  revision = "v1.15.0"
  path = "google"
