// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hardware/hardware.proto

package hardware

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushRequest struct {
	Data                 *Hardware `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{0}
}

func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (m *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(m, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetData() *Hardware {
	if m != nil {
		return m.Data
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type GetRequest struct {
	Mac                  string   `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *GetRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Hardware struct {
	OBSOLETE_JSON        string              `protobuf:"bytes,1,opt,name=OBSOLETE_JSON,json=OBSOLETEJSON,proto3" json:"OBSOLETE_JSON,omitempty"`
	OBSOLETEDhcp         *Hardware_DHCP      `protobuf:"bytes,2,opt,name=OBSOLETE_dhcp,json=OBSOLETEDhcp,proto3" json:"OBSOLETE_dhcp,omitempty"`
	OBSOLETENetboot      *Hardware_Netboot   `protobuf:"bytes,3,opt,name=OBSOLETE_netboot,json=OBSOLETENetboot,proto3" json:"OBSOLETE_netboot,omitempty"`
	OBSOLETENetwork      []*Hardware_Network `protobuf:"bytes,4,rep,name=OBSOLETE_network,json=OBSOLETENetwork,proto3" json:"OBSOLETE_network,omitempty"`
	Metadata             *Hardware_Metadata  `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Network              *Hardware_Network   `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	Id                   string              `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	Version              int64               `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Hardware) Reset()         { *m = Hardware{} }
func (m *Hardware) String() string { return proto.CompactTextString(m) }
func (*Hardware) ProtoMessage()    {}
func (*Hardware) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3}
}

func (m *Hardware) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware.Unmarshal(m, b)
}
func (m *Hardware) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware.Marshal(b, m, deterministic)
}
func (m *Hardware) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware.Merge(m, src)
}
func (m *Hardware) XXX_Size() int {
	return xxx_messageInfo_Hardware.Size(m)
}
func (m *Hardware) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware proto.InternalMessageInfo

func (m *Hardware) GetOBSOLETE_JSON() string {
	if m != nil {
		return m.OBSOLETE_JSON
	}
	return ""
}

func (m *Hardware) GetOBSOLETEDhcp() *Hardware_DHCP {
	if m != nil {
		return m.OBSOLETEDhcp
	}
	return nil
}

func (m *Hardware) GetOBSOLETENetboot() *Hardware_Netboot {
	if m != nil {
		return m.OBSOLETENetboot
	}
	return nil
}

func (m *Hardware) GetOBSOLETENetwork() []*Hardware_Network {
	if m != nil {
		return m.OBSOLETENetwork
	}
	return nil
}

func (m *Hardware) GetMetadata() *Hardware_Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Hardware) GetNetwork() *Hardware_Network {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *Hardware) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Hardware) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type Hardware_DHCP struct {
	Mac                  string            `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	OBSOLETEIp           string            `protobuf:"bytes,2,opt,name=OBSOLETE_ip,json=OBSOLETEIp,proto3" json:"OBSOLETE_ip,omitempty"`
	Hostname             string            `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	LeaseTime            int64             `protobuf:"varint,4,opt,name=lease_time,json=leaseTime,proto3" json:"lease_time,omitempty"`
	NameServers          []string          `protobuf:"bytes,5,rep,name=name_servers,json=nameServers,proto3" json:"name_servers,omitempty"`
	TimeServers          []string          `protobuf:"bytes,6,rep,name=time_servers,json=timeServers,proto3" json:"time_servers,omitempty"`
	OBSOLETEGateway      string            `protobuf:"bytes,7,opt,name=OBSOLETE_gateway,json=OBSOLETEGateway,proto3" json:"OBSOLETE_gateway,omitempty"`
	Arch                 string            `protobuf:"bytes,8,opt,name=arch,proto3" json:"arch,omitempty"`
	Uefi                 bool              `protobuf:"varint,9,opt,name=uefi,proto3" json:"uefi,omitempty"`
	IfaceName            string            `protobuf:"bytes,10,opt,name=iface_name,json=ifaceName,proto3" json:"iface_name,omitempty"`
	Ip                   *Hardware_DHCP_IP `protobuf:"bytes,11,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Hardware_DHCP) Reset()         { *m = Hardware_DHCP{} }
func (m *Hardware_DHCP) String() string { return proto.CompactTextString(m) }
func (*Hardware_DHCP) ProtoMessage()    {}
func (*Hardware_DHCP) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 0}
}

func (m *Hardware_DHCP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_DHCP.Unmarshal(m, b)
}
func (m *Hardware_DHCP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_DHCP.Marshal(b, m, deterministic)
}
func (m *Hardware_DHCP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_DHCP.Merge(m, src)
}
func (m *Hardware_DHCP) XXX_Size() int {
	return xxx_messageInfo_Hardware_DHCP.Size(m)
}
func (m *Hardware_DHCP) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_DHCP.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_DHCP proto.InternalMessageInfo

func (m *Hardware_DHCP) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *Hardware_DHCP) GetOBSOLETEIp() string {
	if m != nil {
		return m.OBSOLETEIp
	}
	return ""
}

func (m *Hardware_DHCP) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Hardware_DHCP) GetLeaseTime() int64 {
	if m != nil {
		return m.LeaseTime
	}
	return 0
}

func (m *Hardware_DHCP) GetNameServers() []string {
	if m != nil {
		return m.NameServers
	}
	return nil
}

func (m *Hardware_DHCP) GetTimeServers() []string {
	if m != nil {
		return m.TimeServers
	}
	return nil
}

func (m *Hardware_DHCP) GetOBSOLETEGateway() string {
	if m != nil {
		return m.OBSOLETEGateway
	}
	return ""
}

func (m *Hardware_DHCP) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *Hardware_DHCP) GetUefi() bool {
	if m != nil {
		return m.Uefi
	}
	return false
}

func (m *Hardware_DHCP) GetIfaceName() string {
	if m != nil {
		return m.IfaceName
	}
	return ""
}

func (m *Hardware_DHCP) GetIp() *Hardware_DHCP_IP {
	if m != nil {
		return m.Ip
	}
	return nil
}

type Hardware_DHCP_IP struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Netmask              string   `protobuf:"bytes,2,opt,name=netmask,proto3" json:"netmask,omitempty"`
	Gateway              string   `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Family               int64    `protobuf:"varint,4,opt,name=family,proto3" json:"family,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hardware_DHCP_IP) Reset()         { *m = Hardware_DHCP_IP{} }
func (m *Hardware_DHCP_IP) String() string { return proto.CompactTextString(m) }
func (*Hardware_DHCP_IP) ProtoMessage()    {}
func (*Hardware_DHCP_IP) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 0, 0}
}

func (m *Hardware_DHCP_IP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_DHCP_IP.Unmarshal(m, b)
}
func (m *Hardware_DHCP_IP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_DHCP_IP.Marshal(b, m, deterministic)
}
func (m *Hardware_DHCP_IP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_DHCP_IP.Merge(m, src)
}
func (m *Hardware_DHCP_IP) XXX_Size() int {
	return xxx_messageInfo_Hardware_DHCP_IP.Size(m)
}
func (m *Hardware_DHCP_IP) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_DHCP_IP.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_DHCP_IP proto.InternalMessageInfo

func (m *Hardware_DHCP_IP) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Hardware_DHCP_IP) GetNetmask() string {
	if m != nil {
		return m.Netmask
	}
	return ""
}

func (m *Hardware_DHCP_IP) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *Hardware_DHCP_IP) GetFamily() int64 {
	if m != nil {
		return m.Family
	}
	return 0
}

type Hardware_Netboot struct {
	AllowPxe             bool                           `protobuf:"varint,1,opt,name=allow_pxe,json=allowPxe,proto3" json:"allow_pxe,omitempty"`
	AllowWorkflow        bool                           `protobuf:"varint,2,opt,name=allow_workflow,json=allowWorkflow,proto3" json:"allow_workflow,omitempty"`
	Ipxe                 *Hardware_Netboot_IPXE         `protobuf:"bytes,3,opt,name=ipxe,proto3" json:"ipxe,omitempty"`
	OBSOLETEBootstrapper *Hardware_Netboot_Bootstrapper `protobuf:"bytes,4,opt,name=OBSOLETE_bootstrapper,json=OBSOLETEBootstrapper,proto3" json:"OBSOLETE_bootstrapper,omitempty"`
	Osie                 *Hardware_Netboot_Osie         `protobuf:"bytes,5,opt,name=osie,proto3" json:"osie,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Hardware_Netboot) Reset()         { *m = Hardware_Netboot{} }
func (m *Hardware_Netboot) String() string { return proto.CompactTextString(m) }
func (*Hardware_Netboot) ProtoMessage()    {}
func (*Hardware_Netboot) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 1}
}

func (m *Hardware_Netboot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Netboot.Unmarshal(m, b)
}
func (m *Hardware_Netboot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Netboot.Marshal(b, m, deterministic)
}
func (m *Hardware_Netboot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Netboot.Merge(m, src)
}
func (m *Hardware_Netboot) XXX_Size() int {
	return xxx_messageInfo_Hardware_Netboot.Size(m)
}
func (m *Hardware_Netboot) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Netboot.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Netboot proto.InternalMessageInfo

func (m *Hardware_Netboot) GetAllowPxe() bool {
	if m != nil {
		return m.AllowPxe
	}
	return false
}

func (m *Hardware_Netboot) GetAllowWorkflow() bool {
	if m != nil {
		return m.AllowWorkflow
	}
	return false
}

func (m *Hardware_Netboot) GetIpxe() *Hardware_Netboot_IPXE {
	if m != nil {
		return m.Ipxe
	}
	return nil
}

func (m *Hardware_Netboot) GetOBSOLETEBootstrapper() *Hardware_Netboot_Bootstrapper {
	if m != nil {
		return m.OBSOLETEBootstrapper
	}
	return nil
}

func (m *Hardware_Netboot) GetOsie() *Hardware_Netboot_Osie {
	if m != nil {
		return m.Osie
	}
	return nil
}

type Hardware_Netboot_IPXE struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Contents             string   `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hardware_Netboot_IPXE) Reset()         { *m = Hardware_Netboot_IPXE{} }
func (m *Hardware_Netboot_IPXE) String() string { return proto.CompactTextString(m) }
func (*Hardware_Netboot_IPXE) ProtoMessage()    {}
func (*Hardware_Netboot_IPXE) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 1, 0}
}

func (m *Hardware_Netboot_IPXE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Netboot_IPXE.Unmarshal(m, b)
}
func (m *Hardware_Netboot_IPXE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Netboot_IPXE.Marshal(b, m, deterministic)
}
func (m *Hardware_Netboot_IPXE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Netboot_IPXE.Merge(m, src)
}
func (m *Hardware_Netboot_IPXE) XXX_Size() int {
	return xxx_messageInfo_Hardware_Netboot_IPXE.Size(m)
}
func (m *Hardware_Netboot_IPXE) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Netboot_IPXE.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Netboot_IPXE proto.InternalMessageInfo

func (m *Hardware_Netboot_IPXE) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Hardware_Netboot_IPXE) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

type Hardware_Netboot_Bootstrapper struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hardware_Netboot_Bootstrapper) Reset()         { *m = Hardware_Netboot_Bootstrapper{} }
func (m *Hardware_Netboot_Bootstrapper) String() string { return proto.CompactTextString(m) }
func (*Hardware_Netboot_Bootstrapper) ProtoMessage()    {}
func (*Hardware_Netboot_Bootstrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 1, 1}
}

func (m *Hardware_Netboot_Bootstrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Netboot_Bootstrapper.Unmarshal(m, b)
}
func (m *Hardware_Netboot_Bootstrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Netboot_Bootstrapper.Marshal(b, m, deterministic)
}
func (m *Hardware_Netboot_Bootstrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Netboot_Bootstrapper.Merge(m, src)
}
func (m *Hardware_Netboot_Bootstrapper) XXX_Size() int {
	return xxx_messageInfo_Hardware_Netboot_Bootstrapper.Size(m)
}
func (m *Hardware_Netboot_Bootstrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Netboot_Bootstrapper.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Netboot_Bootstrapper proto.InternalMessageInfo

type Hardware_Netboot_Osie struct {
	BaseUrl              string   `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Kernel               string   `protobuf:"bytes,2,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Initrd               string   `protobuf:"bytes,3,opt,name=initrd,proto3" json:"initrd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hardware_Netboot_Osie) Reset()         { *m = Hardware_Netboot_Osie{} }
func (m *Hardware_Netboot_Osie) String() string { return proto.CompactTextString(m) }
func (*Hardware_Netboot_Osie) ProtoMessage()    {}
func (*Hardware_Netboot_Osie) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 1, 2}
}

func (m *Hardware_Netboot_Osie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Netboot_Osie.Unmarshal(m, b)
}
func (m *Hardware_Netboot_Osie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Netboot_Osie.Marshal(b, m, deterministic)
}
func (m *Hardware_Netboot_Osie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Netboot_Osie.Merge(m, src)
}
func (m *Hardware_Netboot_Osie) XXX_Size() int {
	return xxx_messageInfo_Hardware_Netboot_Osie.Size(m)
}
func (m *Hardware_Netboot_Osie) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Netboot_Osie.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Netboot_Osie proto.InternalMessageInfo

func (m *Hardware_Netboot_Osie) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

func (m *Hardware_Netboot_Osie) GetKernel() string {
	if m != nil {
		return m.Kernel
	}
	return ""
}

func (m *Hardware_Netboot_Osie) GetInitrd() string {
	if m != nil {
		return m.Initrd
	}
	return ""
}

type Hardware_Network struct {
	OBSOLETEDhcp         *Hardware_DHCP                `protobuf:"bytes,1,opt,name=OBSOLETE_dhcp,json=OBSOLETEDhcp,proto3" json:"OBSOLETE_dhcp,omitempty"`
	OBSOLETENetboot      *Hardware_Netboot             `protobuf:"bytes,2,opt,name=OBSOLETE_netboot,json=OBSOLETENetboot,proto3" json:"OBSOLETE_netboot,omitempty"`
	Interfaces           []*Hardware_Network_Interface `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	OBSOLETEDefault      *Hardware_Network_Interface   `protobuf:"bytes,4,opt,name=OBSOLETE_default,json=OBSOLETEDefault,proto3" json:"OBSOLETE_default,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Hardware_Network) Reset()         { *m = Hardware_Network{} }
func (m *Hardware_Network) String() string { return proto.CompactTextString(m) }
func (*Hardware_Network) ProtoMessage()    {}
func (*Hardware_Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 2}
}

func (m *Hardware_Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Network.Unmarshal(m, b)
}
func (m *Hardware_Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Network.Marshal(b, m, deterministic)
}
func (m *Hardware_Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Network.Merge(m, src)
}
func (m *Hardware_Network) XXX_Size() int {
	return xxx_messageInfo_Hardware_Network.Size(m)
}
func (m *Hardware_Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Network proto.InternalMessageInfo

func (m *Hardware_Network) GetOBSOLETEDhcp() *Hardware_DHCP {
	if m != nil {
		return m.OBSOLETEDhcp
	}
	return nil
}

func (m *Hardware_Network) GetOBSOLETENetboot() *Hardware_Netboot {
	if m != nil {
		return m.OBSOLETENetboot
	}
	return nil
}

func (m *Hardware_Network) GetInterfaces() []*Hardware_Network_Interface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *Hardware_Network) GetOBSOLETEDefault() *Hardware_Network_Interface {
	if m != nil {
		return m.OBSOLETEDefault
	}
	return nil
}

type Hardware_Network_Interface struct {
	Dhcp                 *Hardware_DHCP    `protobuf:"bytes,1,opt,name=dhcp,proto3" json:"dhcp,omitempty"`
	Netboot              *Hardware_Netboot `protobuf:"bytes,2,opt,name=netboot,proto3" json:"netboot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Hardware_Network_Interface) Reset()         { *m = Hardware_Network_Interface{} }
func (m *Hardware_Network_Interface) String() string { return proto.CompactTextString(m) }
func (*Hardware_Network_Interface) ProtoMessage()    {}
func (*Hardware_Network_Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 2, 0}
}

func (m *Hardware_Network_Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Network_Interface.Unmarshal(m, b)
}
func (m *Hardware_Network_Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Network_Interface.Marshal(b, m, deterministic)
}
func (m *Hardware_Network_Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Network_Interface.Merge(m, src)
}
func (m *Hardware_Network_Interface) XXX_Size() int {
	return xxx_messageInfo_Hardware_Network_Interface.Size(m)
}
func (m *Hardware_Network_Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Network_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Network_Interface proto.InternalMessageInfo

func (m *Hardware_Network_Interface) GetDhcp() *Hardware_DHCP {
	if m != nil {
		return m.Dhcp
	}
	return nil
}

func (m *Hardware_Network_Interface) GetNetboot() *Hardware_Netboot {
	if m != nil {
		return m.Netboot
	}
	return nil
}

type Hardware_Metadata struct {
	State                string                          `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	BondingMode          int64                           `protobuf:"varint,2,opt,name=bonding_mode,json=bondingMode,proto3" json:"bonding_mode,omitempty"`
	Manufacturer         *Hardware_Metadata_Manufacturer `protobuf:"bytes,3,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Instance             *Hardware_Metadata_Instance     `protobuf:"bytes,4,opt,name=instance,proto3" json:"instance,omitempty"`
	Custom               *Hardware_Metadata_Custom       `protobuf:"bytes,5,opt,name=custom,proto3" json:"custom,omitempty"`
	Facility             *Hardware_Metadata_Facility     `protobuf:"bytes,6,opt,name=facility,proto3" json:"facility,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Hardware_Metadata) Reset()         { *m = Hardware_Metadata{} }
func (m *Hardware_Metadata) String() string { return proto.CompactTextString(m) }
func (*Hardware_Metadata) ProtoMessage()    {}
func (*Hardware_Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3}
}

func (m *Hardware_Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata.Unmarshal(m, b)
}
func (m *Hardware_Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata.Merge(m, src)
}
func (m *Hardware_Metadata) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata.Size(m)
}
func (m *Hardware_Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata proto.InternalMessageInfo

func (m *Hardware_Metadata) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Hardware_Metadata) GetBondingMode() int64 {
	if m != nil {
		return m.BondingMode
	}
	return 0
}

func (m *Hardware_Metadata) GetManufacturer() *Hardware_Metadata_Manufacturer {
	if m != nil {
		return m.Manufacturer
	}
	return nil
}

func (m *Hardware_Metadata) GetInstance() *Hardware_Metadata_Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *Hardware_Metadata) GetCustom() *Hardware_Metadata_Custom {
	if m != nil {
		return m.Custom
	}
	return nil
}

func (m *Hardware_Metadata) GetFacility() *Hardware_Metadata_Facility {
	if m != nil {
		return m.Facility
	}
	return nil
}

type Hardware_Metadata_Manufacturer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hardware_Metadata_Manufacturer) Reset()         { *m = Hardware_Metadata_Manufacturer{} }
func (m *Hardware_Metadata_Manufacturer) String() string { return proto.CompactTextString(m) }
func (*Hardware_Metadata_Manufacturer) ProtoMessage()    {}
func (*Hardware_Metadata_Manufacturer) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3, 0}
}

func (m *Hardware_Metadata_Manufacturer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata_Manufacturer.Unmarshal(m, b)
}
func (m *Hardware_Metadata_Manufacturer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata_Manufacturer.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata_Manufacturer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata_Manufacturer.Merge(m, src)
}
func (m *Hardware_Metadata_Manufacturer) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata_Manufacturer.Size(m)
}
func (m *Hardware_Metadata_Manufacturer) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata_Manufacturer.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata_Manufacturer proto.InternalMessageInfo

func (m *Hardware_Metadata_Manufacturer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Hardware_Metadata_Manufacturer) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type Hardware_Metadata_Instance struct {
	Id                   string                                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State                string                                      `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Hostname             string                                      `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AllowPxe             bool                                        `protobuf:"varint,4,opt,name=allow_pxe,json=allowPxe,proto3" json:"allow_pxe,omitempty"`
	Rescue               bool                                        `protobuf:"varint,5,opt,name=rescue,proto3" json:"rescue,omitempty"`
	OS                   *Hardware_Metadata_Instance_OperatingSystem `protobuf:"bytes,6,opt,name=OS,proto3" json:"OS,omitempty"`
	AlwaysPxe            bool                                        `protobuf:"varint,7,opt,name=always_pxe,json=alwaysPxe,proto3" json:"always_pxe,omitempty"`
	IpxeScriptUrl        string                                      `protobuf:"bytes,8,opt,name=ipxe_script_url,json=ipxeScriptUrl,proto3" json:"ipxe_script_url,omitempty"`
	Ips                  []*Hardware_Metadata_Instance_IP            `protobuf:"bytes,9,rep,name=ips,proto3" json:"ips,omitempty"`
	Userdata             string                                      `protobuf:"bytes,10,opt,name=userdata,proto3" json:"userdata,omitempty"`
	CryptedRootPassword  string                                      `protobuf:"bytes,11,opt,name=crypted_root_password,json=cryptedRootPassword,proto3" json:"crypted_root_password,omitempty"`
	Tags                 []string                                    `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	Storage              *Hardware_Metadata_Instance_Storage         `protobuf:"bytes,13,opt,name=storage,proto3" json:"storage,omitempty"`
	SshKeys              []string                                    `protobuf:"bytes,14,rep,name=ssh_keys,json=sshKeys,proto3" json:"ssh_keys,omitempty"`
	NetworkReady         bool                                        `protobuf:"varint,15,opt,name=network_ready,json=networkReady,proto3" json:"network_ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *Hardware_Metadata_Instance) Reset()         { *m = Hardware_Metadata_Instance{} }
func (m *Hardware_Metadata_Instance) String() string { return proto.CompactTextString(m) }
func (*Hardware_Metadata_Instance) ProtoMessage()    {}
func (*Hardware_Metadata_Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3, 1}
}

func (m *Hardware_Metadata_Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata_Instance.Unmarshal(m, b)
}
func (m *Hardware_Metadata_Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata_Instance.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata_Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata_Instance.Merge(m, src)
}
func (m *Hardware_Metadata_Instance) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata_Instance.Size(m)
}
func (m *Hardware_Metadata_Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata_Instance proto.InternalMessageInfo

func (m *Hardware_Metadata_Instance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Hardware_Metadata_Instance) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Hardware_Metadata_Instance) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Hardware_Metadata_Instance) GetAllowPxe() bool {
	if m != nil {
		return m.AllowPxe
	}
	return false
}

func (m *Hardware_Metadata_Instance) GetRescue() bool {
	if m != nil {
		return m.Rescue
	}
	return false
}

func (m *Hardware_Metadata_Instance) GetOS() *Hardware_Metadata_Instance_OperatingSystem {
	if m != nil {
		return m.OS
	}
	return nil
}

func (m *Hardware_Metadata_Instance) GetAlwaysPxe() bool {
	if m != nil {
		return m.AlwaysPxe
	}
	return false
}

func (m *Hardware_Metadata_Instance) GetIpxeScriptUrl() string {
	if m != nil {
		return m.IpxeScriptUrl
	}
	return ""
}

func (m *Hardware_Metadata_Instance) GetIps() []*Hardware_Metadata_Instance_IP {
	if m != nil {
		return m.Ips
	}
	return nil
}

func (m *Hardware_Metadata_Instance) GetUserdata() string {
	if m != nil {
		return m.Userdata
	}
	return ""
}

func (m *Hardware_Metadata_Instance) GetCryptedRootPassword() string {
	if m != nil {
		return m.CryptedRootPassword
	}
	return ""
}

func (m *Hardware_Metadata_Instance) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Hardware_Metadata_Instance) GetStorage() *Hardware_Metadata_Instance_Storage {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *Hardware_Metadata_Instance) GetSshKeys() []string {
	if m != nil {
		return m.SshKeys
	}
	return nil
}

func (m *Hardware_Metadata_Instance) GetNetworkReady() bool {
	if m != nil {
		return m.NetworkReady
	}
	return false
}

type Hardware_Metadata_Instance_OperatingSystem struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Distro               string   `protobuf:"bytes,2,opt,name=distro,proto3" json:"distro,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ImageTag             string   `protobuf:"bytes,4,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	OsSlug               string   `protobuf:"bytes,5,opt,name=os_slug,json=osSlug,proto3" json:"os_slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hardware_Metadata_Instance_OperatingSystem) Reset() {
	*m = Hardware_Metadata_Instance_OperatingSystem{}
}
func (m *Hardware_Metadata_Instance_OperatingSystem) String() string {
	return proto.CompactTextString(m)
}
func (*Hardware_Metadata_Instance_OperatingSystem) ProtoMessage() {}
func (*Hardware_Metadata_Instance_OperatingSystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3, 1, 0}
}

func (m *Hardware_Metadata_Instance_OperatingSystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata_Instance_OperatingSystem.Unmarshal(m, b)
}
func (m *Hardware_Metadata_Instance_OperatingSystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata_Instance_OperatingSystem.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata_Instance_OperatingSystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata_Instance_OperatingSystem.Merge(m, src)
}
func (m *Hardware_Metadata_Instance_OperatingSystem) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata_Instance_OperatingSystem.Size(m)
}
func (m *Hardware_Metadata_Instance_OperatingSystem) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata_Instance_OperatingSystem.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata_Instance_OperatingSystem proto.InternalMessageInfo

func (m *Hardware_Metadata_Instance_OperatingSystem) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Hardware_Metadata_Instance_OperatingSystem) GetDistro() string {
	if m != nil {
		return m.Distro
	}
	return ""
}

func (m *Hardware_Metadata_Instance_OperatingSystem) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Hardware_Metadata_Instance_OperatingSystem) GetImageTag() string {
	if m != nil {
		return m.ImageTag
	}
	return ""
}

func (m *Hardware_Metadata_Instance_OperatingSystem) GetOsSlug() string {
	if m != nil {
		return m.OsSlug
	}
	return ""
}

type Hardware_Metadata_Instance_IP struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Netmask              string   `protobuf:"bytes,2,opt,name=netmask,proto3" json:"netmask,omitempty"`
	Gateway              string   `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Family               int64    `protobuf:"varint,4,opt,name=family,proto3" json:"family,omitempty"`
	Public               bool     `protobuf:"varint,5,opt,name=public,proto3" json:"public,omitempty"`
	Management           bool     `protobuf:"varint,6,opt,name=management,proto3" json:"management,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hardware_Metadata_Instance_IP) Reset()         { *m = Hardware_Metadata_Instance_IP{} }
func (m *Hardware_Metadata_Instance_IP) String() string { return proto.CompactTextString(m) }
func (*Hardware_Metadata_Instance_IP) ProtoMessage()    {}
func (*Hardware_Metadata_Instance_IP) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3, 1, 1}
}

func (m *Hardware_Metadata_Instance_IP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata_Instance_IP.Unmarshal(m, b)
}
func (m *Hardware_Metadata_Instance_IP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata_Instance_IP.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata_Instance_IP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata_Instance_IP.Merge(m, src)
}
func (m *Hardware_Metadata_Instance_IP) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata_Instance_IP.Size(m)
}
func (m *Hardware_Metadata_Instance_IP) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata_Instance_IP.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata_Instance_IP proto.InternalMessageInfo

func (m *Hardware_Metadata_Instance_IP) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Hardware_Metadata_Instance_IP) GetNetmask() string {
	if m != nil {
		return m.Netmask
	}
	return ""
}

func (m *Hardware_Metadata_Instance_IP) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *Hardware_Metadata_Instance_IP) GetFamily() int64 {
	if m != nil {
		return m.Family
	}
	return 0
}

func (m *Hardware_Metadata_Instance_IP) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *Hardware_Metadata_Instance_IP) GetManagement() bool {
	if m != nil {
		return m.Management
	}
	return false
}

type Hardware_Metadata_Instance_Storage struct {
	OBSOLETEDisks        []string                                         `protobuf:"bytes,1,rep,name=OBSOLETE_disks,json=OBSOLETEDisks,proto3" json:"OBSOLETE_disks,omitempty"`
	OBSOLETERaid         []string                                         `protobuf:"bytes,2,rep,name=OBSOLETE_raid,json=OBSOLETERaid,proto3" json:"OBSOLETE_raid,omitempty"`
	OBSOLETEFilesystems  []string                                         `protobuf:"bytes,3,rep,name=OBSOLETE_filesystems,json=OBSOLETEFilesystems,proto3" json:"OBSOLETE_filesystems,omitempty"`
	Disks                []*Hardware_Metadata_Instance_Storage_Disk       `protobuf:"bytes,4,rep,name=disks,proto3" json:"disks,omitempty"`
	Raid                 []*Hardware_Metadata_Instance_Storage_RAID       `protobuf:"bytes,5,rep,name=raid,proto3" json:"raid,omitempty"`
	Filesystems          []*Hardware_Metadata_Instance_Storage_Filesystem `protobuf:"bytes,6,rep,name=filesystems,proto3" json:"filesystems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                         `json:"-"`
	XXX_unrecognized     []byte                                           `json:"-"`
	XXX_sizecache        int32                                            `json:"-"`
}

func (m *Hardware_Metadata_Instance_Storage) Reset()         { *m = Hardware_Metadata_Instance_Storage{} }
func (m *Hardware_Metadata_Instance_Storage) String() string { return proto.CompactTextString(m) }
func (*Hardware_Metadata_Instance_Storage) ProtoMessage()    {}
func (*Hardware_Metadata_Instance_Storage) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3, 1, 2}
}

func (m *Hardware_Metadata_Instance_Storage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage.Unmarshal(m, b)
}
func (m *Hardware_Metadata_Instance_Storage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata_Instance_Storage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage.Merge(m, src)
}
func (m *Hardware_Metadata_Instance_Storage) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage.Size(m)
}
func (m *Hardware_Metadata_Instance_Storage) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata_Instance_Storage proto.InternalMessageInfo

func (m *Hardware_Metadata_Instance_Storage) GetOBSOLETEDisks() []string {
	if m != nil {
		return m.OBSOLETEDisks
	}
	return nil
}

func (m *Hardware_Metadata_Instance_Storage) GetOBSOLETERaid() []string {
	if m != nil {
		return m.OBSOLETERaid
	}
	return nil
}

func (m *Hardware_Metadata_Instance_Storage) GetOBSOLETEFilesystems() []string {
	if m != nil {
		return m.OBSOLETEFilesystems
	}
	return nil
}

func (m *Hardware_Metadata_Instance_Storage) GetDisks() []*Hardware_Metadata_Instance_Storage_Disk {
	if m != nil {
		return m.Disks
	}
	return nil
}

func (m *Hardware_Metadata_Instance_Storage) GetRaid() []*Hardware_Metadata_Instance_Storage_RAID {
	if m != nil {
		return m.Raid
	}
	return nil
}

func (m *Hardware_Metadata_Instance_Storage) GetFilesystems() []*Hardware_Metadata_Instance_Storage_Filesystem {
	if m != nil {
		return m.Filesystems
	}
	return nil
}

type Hardware_Metadata_Instance_Storage_Disk struct {
	Device               string                                               `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	WipeTable            bool                                                 `protobuf:"varint,2,opt,name=wipe_table,json=wipeTable,proto3" json:"wipe_table,omitempty"`
	Partitions           []*Hardware_Metadata_Instance_Storage_Disk_Partition `protobuf:"bytes,3,rep,name=partitions,proto3" json:"partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                             `json:"-"`
	XXX_unrecognized     []byte                                               `json:"-"`
	XXX_sizecache        int32                                                `json:"-"`
}

func (m *Hardware_Metadata_Instance_Storage_Disk) Reset() {
	*m = Hardware_Metadata_Instance_Storage_Disk{}
}
func (m *Hardware_Metadata_Instance_Storage_Disk) String() string { return proto.CompactTextString(m) }
func (*Hardware_Metadata_Instance_Storage_Disk) ProtoMessage()    {}
func (*Hardware_Metadata_Instance_Storage_Disk) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3, 1, 2, 0}
}

func (m *Hardware_Metadata_Instance_Storage_Disk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Disk.Unmarshal(m, b)
}
func (m *Hardware_Metadata_Instance_Storage_Disk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Disk.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata_Instance_Storage_Disk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage_Disk.Merge(m, src)
}
func (m *Hardware_Metadata_Instance_Storage_Disk) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Disk.Size(m)
}
func (m *Hardware_Metadata_Instance_Storage_Disk) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage_Disk.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata_Instance_Storage_Disk proto.InternalMessageInfo

func (m *Hardware_Metadata_Instance_Storage_Disk) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *Hardware_Metadata_Instance_Storage_Disk) GetWipeTable() bool {
	if m != nil {
		return m.WipeTable
	}
	return false
}

func (m *Hardware_Metadata_Instance_Storage_Disk) GetPartitions() []*Hardware_Metadata_Instance_Storage_Disk_Partition {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type Hardware_Metadata_Instance_Storage_Disk_Partition struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Number               int64    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Start                int64    `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"`
	TypeGuid             string   `protobuf:"bytes,5,opt,name=type_guid,json=typeGuid,proto3" json:"type_guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hardware_Metadata_Instance_Storage_Disk_Partition) Reset() {
	*m = Hardware_Metadata_Instance_Storage_Disk_Partition{}
}
func (m *Hardware_Metadata_Instance_Storage_Disk_Partition) String() string {
	return proto.CompactTextString(m)
}
func (*Hardware_Metadata_Instance_Storage_Disk_Partition) ProtoMessage() {}
func (*Hardware_Metadata_Instance_Storage_Disk_Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3, 1, 2, 0, 0}
}

func (m *Hardware_Metadata_Instance_Storage_Disk_Partition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Disk_Partition.Unmarshal(m, b)
}
func (m *Hardware_Metadata_Instance_Storage_Disk_Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Disk_Partition.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata_Instance_Storage_Disk_Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage_Disk_Partition.Merge(m, src)
}
func (m *Hardware_Metadata_Instance_Storage_Disk_Partition) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Disk_Partition.Size(m)
}
func (m *Hardware_Metadata_Instance_Storage_Disk_Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage_Disk_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata_Instance_Storage_Disk_Partition proto.InternalMessageInfo

func (m *Hardware_Metadata_Instance_Storage_Disk_Partition) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Hardware_Metadata_Instance_Storage_Disk_Partition) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Hardware_Metadata_Instance_Storage_Disk_Partition) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Hardware_Metadata_Instance_Storage_Disk_Partition) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Hardware_Metadata_Instance_Storage_Disk_Partition) GetTypeGuid() string {
	if m != nil {
		return m.TypeGuid
	}
	return ""
}

type Hardware_Metadata_Instance_Storage_File struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Contents             string   `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	Mode                 int64    `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid                  int64    `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  int64    `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hardware_Metadata_Instance_Storage_File) Reset() {
	*m = Hardware_Metadata_Instance_Storage_File{}
}
func (m *Hardware_Metadata_Instance_Storage_File) String() string { return proto.CompactTextString(m) }
func (*Hardware_Metadata_Instance_Storage_File) ProtoMessage()    {}
func (*Hardware_Metadata_Instance_Storage_File) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3, 1, 2, 1}
}

func (m *Hardware_Metadata_Instance_Storage_File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_File.Unmarshal(m, b)
}
func (m *Hardware_Metadata_Instance_Storage_File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_File.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata_Instance_Storage_File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage_File.Merge(m, src)
}
func (m *Hardware_Metadata_Instance_Storage_File) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_File.Size(m)
}
func (m *Hardware_Metadata_Instance_Storage_File) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage_File.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata_Instance_Storage_File proto.InternalMessageInfo

func (m *Hardware_Metadata_Instance_Storage_File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Hardware_Metadata_Instance_Storage_File) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

func (m *Hardware_Metadata_Instance_Storage_File) GetMode() int64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *Hardware_Metadata_Instance_Storage_File) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Hardware_Metadata_Instance_Storage_File) GetGid() int64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

type Hardware_Metadata_Instance_Storage_Mount struct {
	Device               string                                                      `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Format               string                                                      `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Files                []*Hardware_Metadata_Instance_Storage_File                  `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	Create               *Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions `protobuf:"bytes,4,opt,name=create,proto3" json:"create,omitempty"`
	Point                string                                                      `protobuf:"bytes,5,opt,name=point,proto3" json:"point,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                    `json:"-"`
	XXX_unrecognized     []byte                                                      `json:"-"`
	XXX_sizecache        int32                                                       `json:"-"`
}

func (m *Hardware_Metadata_Instance_Storage_Mount) Reset() {
	*m = Hardware_Metadata_Instance_Storage_Mount{}
}
func (m *Hardware_Metadata_Instance_Storage_Mount) String() string { return proto.CompactTextString(m) }
func (*Hardware_Metadata_Instance_Storage_Mount) ProtoMessage()    {}
func (*Hardware_Metadata_Instance_Storage_Mount) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3, 1, 2, 2}
}

func (m *Hardware_Metadata_Instance_Storage_Mount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Mount.Unmarshal(m, b)
}
func (m *Hardware_Metadata_Instance_Storage_Mount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Mount.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata_Instance_Storage_Mount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage_Mount.Merge(m, src)
}
func (m *Hardware_Metadata_Instance_Storage_Mount) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Mount.Size(m)
}
func (m *Hardware_Metadata_Instance_Storage_Mount) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage_Mount.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata_Instance_Storage_Mount proto.InternalMessageInfo

func (m *Hardware_Metadata_Instance_Storage_Mount) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *Hardware_Metadata_Instance_Storage_Mount) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Hardware_Metadata_Instance_Storage_Mount) GetFiles() []*Hardware_Metadata_Instance_Storage_File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *Hardware_Metadata_Instance_Storage_Mount) GetCreate() *Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions {
	if m != nil {
		return m.Create
	}
	return nil
}

func (m *Hardware_Metadata_Instance_Storage_Mount) GetPoint() string {
	if m != nil {
		return m.Point
	}
	return ""
}

type Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions struct {
	Force                bool     `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	Options              []string `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions) Reset() {
	*m = Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions{}
}
func (m *Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions) String() string {
	return proto.CompactTextString(m)
}
func (*Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions) ProtoMessage() {}
func (*Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3, 1, 2, 2, 0}
}

func (m *Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions.Unmarshal(m, b)
}
func (m *Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions.Merge(m, src)
}
func (m *Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions.Size(m)
}
func (m *Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions proto.InternalMessageInfo

func (m *Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

type Hardware_Metadata_Instance_Storage_Filesystem struct {
	Mount                *Hardware_Metadata_Instance_Storage_Mount `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *Hardware_Metadata_Instance_Storage_Filesystem) Reset() {
	*m = Hardware_Metadata_Instance_Storage_Filesystem{}
}
func (m *Hardware_Metadata_Instance_Storage_Filesystem) String() string {
	return proto.CompactTextString(m)
}
func (*Hardware_Metadata_Instance_Storage_Filesystem) ProtoMessage() {}
func (*Hardware_Metadata_Instance_Storage_Filesystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3, 1, 2, 3}
}

func (m *Hardware_Metadata_Instance_Storage_Filesystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Filesystem.Unmarshal(m, b)
}
func (m *Hardware_Metadata_Instance_Storage_Filesystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Filesystem.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata_Instance_Storage_Filesystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage_Filesystem.Merge(m, src)
}
func (m *Hardware_Metadata_Instance_Storage_Filesystem) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_Filesystem.Size(m)
}
func (m *Hardware_Metadata_Instance_Storage_Filesystem) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage_Filesystem.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata_Instance_Storage_Filesystem proto.InternalMessageInfo

func (m *Hardware_Metadata_Instance_Storage_Filesystem) GetMount() *Hardware_Metadata_Instance_Storage_Mount {
	if m != nil {
		return m.Mount
	}
	return nil
}

type Hardware_Metadata_Instance_Storage_RAID struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Level                string   `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Devices              []string `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	Spare                int64    `protobuf:"varint,4,opt,name=spare,proto3" json:"spare,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hardware_Metadata_Instance_Storage_RAID) Reset() {
	*m = Hardware_Metadata_Instance_Storage_RAID{}
}
func (m *Hardware_Metadata_Instance_Storage_RAID) String() string { return proto.CompactTextString(m) }
func (*Hardware_Metadata_Instance_Storage_RAID) ProtoMessage()    {}
func (*Hardware_Metadata_Instance_Storage_RAID) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3, 1, 2, 4}
}

func (m *Hardware_Metadata_Instance_Storage_RAID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_RAID.Unmarshal(m, b)
}
func (m *Hardware_Metadata_Instance_Storage_RAID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_RAID.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata_Instance_Storage_RAID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage_RAID.Merge(m, src)
}
func (m *Hardware_Metadata_Instance_Storage_RAID) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata_Instance_Storage_RAID.Size(m)
}
func (m *Hardware_Metadata_Instance_Storage_RAID) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata_Instance_Storage_RAID.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata_Instance_Storage_RAID proto.InternalMessageInfo

func (m *Hardware_Metadata_Instance_Storage_RAID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hardware_Metadata_Instance_Storage_RAID) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *Hardware_Metadata_Instance_Storage_RAID) GetDevices() []string {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *Hardware_Metadata_Instance_Storage_RAID) GetSpare() int64 {
	if m != nil {
		return m.Spare
	}
	return 0
}

type Hardware_Metadata_Custom struct {
	PreinstalledOs       *Hardware_Metadata_Instance_OperatingSystem `protobuf:"bytes,1,opt,name=preinstalled_os,json=preinstalledOs,proto3" json:"preinstalled_os,omitempty"`
	PrivateSubnets       []string                                    `protobuf:"bytes,2,rep,name=private_subnets,json=privateSubnets,proto3" json:"private_subnets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *Hardware_Metadata_Custom) Reset()         { *m = Hardware_Metadata_Custom{} }
func (m *Hardware_Metadata_Custom) String() string { return proto.CompactTextString(m) }
func (*Hardware_Metadata_Custom) ProtoMessage()    {}
func (*Hardware_Metadata_Custom) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3, 2}
}

func (m *Hardware_Metadata_Custom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata_Custom.Unmarshal(m, b)
}
func (m *Hardware_Metadata_Custom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata_Custom.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata_Custom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata_Custom.Merge(m, src)
}
func (m *Hardware_Metadata_Custom) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata_Custom.Size(m)
}
func (m *Hardware_Metadata_Custom) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata_Custom.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata_Custom proto.InternalMessageInfo

func (m *Hardware_Metadata_Custom) GetPreinstalledOs() *Hardware_Metadata_Instance_OperatingSystem {
	if m != nil {
		return m.PreinstalledOs
	}
	return nil
}

func (m *Hardware_Metadata_Custom) GetPrivateSubnets() []string {
	if m != nil {
		return m.PrivateSubnets
	}
	return nil
}

type Hardware_Metadata_Facility struct {
	PlanSlug             string   `protobuf:"bytes,1,opt,name=plan_slug,json=planSlug,proto3" json:"plan_slug,omitempty"`
	PlanVersionSlug      string   `protobuf:"bytes,2,opt,name=plan_version_slug,json=planVersionSlug,proto3" json:"plan_version_slug,omitempty"`
	FacilityCode         string   `protobuf:"bytes,3,opt,name=facility_code,json=facilityCode,proto3" json:"facility_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hardware_Metadata_Facility) Reset()         { *m = Hardware_Metadata_Facility{} }
func (m *Hardware_Metadata_Facility) String() string { return proto.CompactTextString(m) }
func (*Hardware_Metadata_Facility) ProtoMessage()    {}
func (*Hardware_Metadata_Facility) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{3, 3, 3}
}

func (m *Hardware_Metadata_Facility) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hardware_Metadata_Facility.Unmarshal(m, b)
}
func (m *Hardware_Metadata_Facility) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hardware_Metadata_Facility.Marshal(b, m, deterministic)
}
func (m *Hardware_Metadata_Facility) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hardware_Metadata_Facility.Merge(m, src)
}
func (m *Hardware_Metadata_Facility) XXX_Size() int {
	return xxx_messageInfo_Hardware_Metadata_Facility.Size(m)
}
func (m *Hardware_Metadata_Facility) XXX_DiscardUnknown() {
	xxx_messageInfo_Hardware_Metadata_Facility.DiscardUnknown(m)
}

var xxx_messageInfo_Hardware_Metadata_Facility proto.InternalMessageInfo

func (m *Hardware_Metadata_Facility) GetPlanSlug() string {
	if m != nil {
		return m.PlanSlug
	}
	return ""
}

func (m *Hardware_Metadata_Facility) GetPlanVersionSlug() string {
	if m != nil {
		return m.PlanVersionSlug
	}
	return ""
}

func (m *Hardware_Metadata_Facility) GetFacilityCode() string {
	if m != nil {
		return m.FacilityCode
	}
	return ""
}

type DeleteRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ac56d7fc2e671f, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*PushRequest)(nil), "github.com.tinkerbell.tink.protos.hardware.PushRequest")
	proto.RegisterType((*Empty)(nil), "github.com.tinkerbell.tink.protos.hardware.Empty")
	proto.RegisterType((*GetRequest)(nil), "github.com.tinkerbell.tink.protos.hardware.GetRequest")
	proto.RegisterType((*Hardware)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware")
	proto.RegisterType((*Hardware_DHCP)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.DHCP")
	proto.RegisterType((*Hardware_DHCP_IP)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.DHCP.IP")
	proto.RegisterType((*Hardware_Netboot)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Netboot")
	proto.RegisterType((*Hardware_Netboot_IPXE)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Netboot.IPXE")
	proto.RegisterType((*Hardware_Netboot_Bootstrapper)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Netboot.Bootstrapper")
	proto.RegisterType((*Hardware_Netboot_Osie)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Netboot.Osie")
	proto.RegisterType((*Hardware_Network)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Network")
	proto.RegisterType((*Hardware_Network_Interface)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Network.Interface")
	proto.RegisterType((*Hardware_Metadata)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata")
	proto.RegisterType((*Hardware_Metadata_Manufacturer)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata.Manufacturer")
	proto.RegisterType((*Hardware_Metadata_Instance)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata.Instance")
	proto.RegisterType((*Hardware_Metadata_Instance_OperatingSystem)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata.Instance.OperatingSystem")
	proto.RegisterType((*Hardware_Metadata_Instance_IP)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata.Instance.IP")
	proto.RegisterType((*Hardware_Metadata_Instance_Storage)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata.Instance.Storage")
	proto.RegisterType((*Hardware_Metadata_Instance_Storage_Disk)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata.Instance.Storage.Disk")
	proto.RegisterType((*Hardware_Metadata_Instance_Storage_Disk_Partition)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata.Instance.Storage.Disk.Partition")
	proto.RegisterType((*Hardware_Metadata_Instance_Storage_File)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata.Instance.Storage.File")
	proto.RegisterType((*Hardware_Metadata_Instance_Storage_Mount)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata.Instance.Storage.Mount")
	proto.RegisterType((*Hardware_Metadata_Instance_Storage_Mount_FilesystemOptions)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata.Instance.Storage.Mount.FilesystemOptions")
	proto.RegisterType((*Hardware_Metadata_Instance_Storage_Filesystem)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata.Instance.Storage.Filesystem")
	proto.RegisterType((*Hardware_Metadata_Instance_Storage_RAID)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata.Instance.Storage.RAID")
	proto.RegisterType((*Hardware_Metadata_Custom)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata.Custom")
	proto.RegisterType((*Hardware_Metadata_Facility)(nil), "github.com.tinkerbell.tink.protos.hardware.Hardware.Metadata.Facility")
	proto.RegisterType((*DeleteRequest)(nil), "github.com.tinkerbell.tink.protos.hardware.DeleteRequest")
}

func init() {
	proto.RegisterFile("hardware/hardware.proto", fileDescriptor_61ac56d7fc2e671f)
}

var fileDescriptor_61ac56d7fc2e671f = []byte{
	// 1996 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x5b, 0x8f, 0x1c, 0x47,
	0x15, 0xd6, 0xdc, 0x76, 0x66, 0xce, 0xec, 0xc5, 0x2e, 0xdb, 0xf1, 0xb8, 0x03, 0xc4, 0x6c, 0x04,
	0x18, 0x23, 0x8d, 0xe3, 0x25, 0x02, 0x81, 0x00, 0xc9, 0xf6, 0xf8, 0x32, 0x21, 0xeb, 0x1d, 0x6a,
	0x1c, 0x9b, 0x70, 0x6b, 0x6a, 0xba, 0x6b, 0x66, 0x2a, 0xdb, 0xb7, 0x74, 0x55, 0xef, 0x7a, 0x88,
	0x12, 0x10, 0x0f, 0xbc, 0x20, 0x04, 0x02, 0xde, 0x91, 0xf8, 0x09, 0x3c, 0xf2, 0xc2, 0x8f, 0xc8,
	0x3f, 0x40, 0x08, 0x7e, 0x03, 0x0f, 0x48, 0xe8, 0xd4, 0xa5, 0xb7, 0xd7, 0x86, 0x28, 0xde, 0xd9,
	0xf5, 0x5b, 0x9d, 0x53, 0xd5, 0xdf, 0xb9, 0xd7, 0x39, 0xd5, 0x70, 0x79, 0xc1, 0xf2, 0xf0, 0x90,
	0xe5, 0xfc, 0x86, 0x5b, 0x0c, 0xb2, 0x3c, 0x55, 0x29, 0xb9, 0x3e, 0x17, 0x6a, 0x51, 0x4c, 0x07,
	0x41, 0x1a, 0x0f, 0x94, 0x48, 0xf6, 0x79, 0x3e, 0xe5, 0x51, 0xa4, 0x97, 0xe6, 0x84, 0x1c, 0xb8,
	0x2f, 0xbc, 0xcf, 0xcc, 0xd3, 0x74, 0x1e, 0xf1, 0x1b, 0x2c, 0x13, 0x37, 0x58, 0x92, 0xa4, 0x8a,
	0x29, 0x91, 0x26, 0xd2, 0x9c, 0xdb, 0x7e, 0x02, 0xbd, 0x71, 0x21, 0x17, 0x94, 0xbf, 0x5f, 0x70,
	0xa9, 0xc8, 0x03, 0x68, 0x86, 0x4c, 0xb1, 0x7e, 0xed, 0x6a, 0xed, 0x5a, 0x6f, 0xe7, 0xcd, 0xc1,
	0xa7, 0x97, 0x33, 0x78, 0x60, 0x17, 0x54, 0x23, 0x6c, 0xb7, 0xa1, 0x75, 0x37, 0xce, 0xd4, 0x72,
	0xfb, 0x3b, 0x00, 0xf7, 0xb9, 0x72, 0x02, 0xce, 0x41, 0x23, 0x66, 0x81, 0xc6, 0xef, 0x52, 0x5c,
	0x92, 0x4d, 0xa8, 0x8b, 0xac, 0x5f, 0xd7, 0x8c, 0xba, 0xc8, 0x34, 0x1d, 0xf6, 0x1b, 0x96, 0x0e,
	0xb7, 0xff, 0xf4, 0x15, 0xe8, 0x38, 0x6c, 0xf2, 0x3a, 0x6c, 0xec, 0xdd, 0x9e, 0xec, 0xbd, 0x7d,
	0xf7, 0xd1, 0x5d, 0xff, 0xad, 0xc9, 0xde, 0x43, 0x0b, 0xb4, 0xee, 0x98, 0xc8, 0x23, 0x3f, 0xa9,
	0x1c, 0x0a, 0x17, 0x81, 0x01, 0xef, 0xed, 0x7c, 0xe3, 0x24, 0xd6, 0x0c, 0x86, 0x0f, 0xee, 0x8c,
	0x8f, 0xf0, 0x87, 0x8b, 0x20, 0x23, 0x73, 0x38, 0x57, 0xe2, 0x27, 0x5c, 0x4d, 0xd3, 0x54, 0x69,
	0x7d, 0x7b, 0x3b, 0xdf, 0x3a, 0x91, 0x88, 0x87, 0x06, 0x83, 0x6e, 0x39, 0x54, 0xcb, 0x78, 0x56,
	0xd0, 0x61, 0x9a, 0xef, 0xf7, 0x9b, 0x57, 0x1b, 0xab, 0x08, 0x42, 0x8c, 0x63, 0x82, 0x90, 0x41,
	0xde, 0x85, 0x4e, 0xcc, 0x15, 0xd3, 0xa1, 0x6f, 0x69, 0x4b, 0xbe, 0x7d, 0x22, 0x01, 0xbb, 0x16,
	0x84, 0x96, 0x70, 0xe4, 0x31, 0xb4, 0x9d, 0xea, 0x6b, 0xab, 0xf9, 0x48, 0xab, 0xee, 0xc0, 0x6c,
	0x9a, 0xb4, 0x5d, 0x9a, 0x90, 0x3e, 0xb4, 0x0f, 0x78, 0x2e, 0x45, 0x9a, 0xf4, 0x3b, 0x57, 0x6b,
	0xd7, 0x1a, 0xd4, 0x91, 0xde, 0x3f, 0x1b, 0xd0, 0xc4, 0x28, 0xfe, 0x8f, 0xdc, 0x7b, 0x0d, 0x7a,
	0xa5, 0x83, 0xcb, 0x24, 0x04, 0xc7, 0x1a, 0x65, 0xc4, 0x83, 0xce, 0x22, 0x95, 0x2a, 0x61, 0x31,
	0xb7, 0x29, 0x59, 0xd2, 0xe4, 0xb3, 0x00, 0x11, 0x67, 0x92, 0xfb, 0x4a, 0xc4, 0xbc, 0xdf, 0xd4,
	0x42, 0xbb, 0x9a, 0xf3, 0x48, 0xc4, 0x9c, 0x7c, 0x1e, 0xd6, 0xf1, 0x98, 0x2f, 0x79, 0x8e, 0x9a,
	0xf4, 0x5b, 0x57, 0x1b, 0xd7, 0xba, 0xb4, 0x87, 0xbc, 0x89, 0x61, 0xe1, 0x11, 0xfc, 0xb6, 0x3c,
	0xb2, 0x66, 0x8e, 0x20, 0xcf, 0x1d, 0xf9, 0x72, 0x25, 0x05, 0xe6, 0x4c, 0xf1, 0x43, 0xb6, 0xb4,
	0x46, 0x97, 0x41, 0xbc, 0x6f, 0xd8, 0x84, 0x40, 0x93, 0xe5, 0xc1, 0x42, 0x9b, 0xdf, 0xa5, 0x7a,
	0x8d, 0xbc, 0x82, 0xcf, 0x44, 0xbf, 0x7b, 0xb5, 0x76, 0xad, 0x43, 0xf5, 0x1a, 0xf5, 0x16, 0x33,
	0x16, 0x70, 0x5f, 0x5b, 0x05, 0xfa, 0x74, 0x57, 0x73, 0x1e, 0xa2, 0x59, 0x6f, 0xeb, 0x7a, 0xec,
	0xad, 0x10, 0x2b, 0x74, 0xf6, 0x60, 0x34, 0xc6, 0x6a, 0xf6, 0xde, 0x83, 0xfa, 0x68, 0x8c, 0xc1,
	0x61, 0x61, 0x98, 0x73, 0x29, 0xad, 0xf7, 0x1d, 0x89, 0x3b, 0x09, 0x57, 0x31, 0x93, 0xfb, 0xd6,
	0xfb, 0x8e, 0xc4, 0x1d, 0x67, 0xb0, 0xf1, 0xbc, 0x23, 0xc9, 0x2b, 0xb0, 0x36, 0x63, 0xb1, 0x88,
	0x96, 0xd6, 0xe9, 0x96, 0xf2, 0xfe, 0xd8, 0x84, 0xb6, 0x2b, 0x9d, 0x57, 0xa1, 0xcb, 0xa2, 0x28,
	0x3d, 0xf4, 0xb3, 0xa7, 0x5c, 0xcb, 0xec, 0xd0, 0x8e, 0x66, 0x8c, 0x9f, 0x72, 0xf2, 0x05, 0xd8,
	0x34, 0x9b, 0x98, 0x49, 0xb3, 0x28, 0x3d, 0xd4, 0xb2, 0x3b, 0x74, 0x43, 0x73, 0x9f, 0x58, 0x26,
	0x79, 0x07, 0x9a, 0x02, 0x3f, 0x37, 0xb5, 0x7d, 0x6b, 0x95, 0xda, 0x1e, 0x8c, 0xc6, 0xdf, 0xbf,
	0x4b, 0x35, 0x1c, 0xf9, 0x08, 0x2e, 0x95, 0x21, 0xc5, 0x3d, 0xa9, 0x72, 0x96, 0x65, 0x3c, 0xd7,
	0xd6, 0xf4, 0x76, 0x46, 0x2b, 0xc9, 0xb9, 0x5d, 0x01, 0xa4, 0x17, 0x9d, 0x9c, 0x2a, 0x17, 0xcd,
	0x4a, 0xa5, 0xe0, 0xb6, 0xd0, 0x57, 0x33, 0x6b, 0x4f, 0x0a, 0x4e, 0x35, 0x9c, 0xf7, 0x26, 0x34,
	0xd1, 0x48, 0xac, 0xb2, 0x22, 0x8f, 0x5c, 0x95, 0x15, 0x79, 0x84, 0x45, 0x14, 0xa4, 0x89, 0xe2,
	0x89, 0x92, 0x36, 0xc8, 0x25, 0xed, 0x6d, 0xc2, 0x7a, 0x55, 0x39, 0xef, 0x7b, 0xd0, 0x44, 0x4c,
	0x72, 0x05, 0x3a, 0x53, 0xac, 0xad, 0x23, 0xa8, 0x36, 0xd2, 0xef, 0xe4, 0x11, 0x86, 0x7f, 0x9f,
	0xe7, 0x09, 0x8f, 0x2c, 0x98, 0xa5, 0x90, 0x2f, 0x12, 0xa1, 0x72, 0xd7, 0x3c, 0x2c, 0xe5, 0xfd,
	0xdd, 0xa4, 0x85, 0xbe, 0x35, 0x9e, 0x6b, 0x0d, 0xb5, 0xb3, 0x6f, 0x0d, 0xf5, 0xb3, 0x68, 0x0d,
	0x33, 0x00, 0x91, 0x28, 0x9e, 0x63, 0xd9, 0xca, 0x7e, 0x43, 0x37, 0x85, 0x7b, 0xab, 0xdc, 0xac,
	0x83, 0x91, 0x83, 0xa3, 0x15, 0x64, 0xf2, 0x7e, 0xc5, 0xa0, 0x90, 0xcf, 0x58, 0x11, 0x29, 0x9b,
	0xa7, 0xa7, 0x25, 0xad, 0x34, 0x6d, 0x68, 0xe0, 0xbd, 0xbf, 0xd4, 0xa0, 0x5b, 0x6e, 0x93, 0x5d,
	0x68, 0x9e, 0x4e, 0xa0, 0x34, 0x8c, 0x6d, 0x47, 0xa7, 0x16, 0x17, 0x07, 0xe6, 0xfd, 0xfb, 0x0a,
	0x74, 0x5c, 0xf7, 0x23, 0x17, 0xa1, 0x25, 0x15, 0x53, 0xdc, 0x66, 0xae, 0x21, 0xf0, 0xb6, 0x9f,
	0xa6, 0x49, 0x28, 0x92, 0xb9, 0x1f, 0xa7, 0x21, 0xd7, 0xf2, 0x1b, 0xb4, 0x67, 0x79, 0xbb, 0x69,
	0xc8, 0x49, 0x02, 0xeb, 0x31, 0x4b, 0x8a, 0x19, 0x0b, 0x54, 0x91, 0xf3, 0xdc, 0xde, 0x3c, 0x6f,
	0xad, 0xd4, 0x8b, 0x07, 0xbb, 0x15, 0x44, 0x7a, 0x0c, 0x9f, 0x4c, 0xa1, 0x23, 0x12, 0xa9, 0x58,
	0x12, 0xf0, 0x95, 0xa2, 0x5a, 0xca, 0x1a, 0x59, 0x34, 0x5a, 0xe2, 0x92, 0x1f, 0xc1, 0x5a, 0x50,
	0x48, 0x95, 0xc6, 0xf6, 0xc2, 0x19, 0xae, 0x26, 0xe1, 0x8e, 0xc6, 0xa2, 0x16, 0x13, 0x2d, 0x98,
	0xb1, 0x40, 0x44, 0x42, 0x2d, 0xed, 0x7c, 0xb1, 0xa2, 0x05, 0xf7, 0x2c, 0x1a, 0x2d, 0x71, 0xbd,
	0x1d, 0x58, 0xaf, 0xfa, 0xd0, 0x8e, 0x1e, 0xb5, 0x72, 0xf4, 0x20, 0xd0, 0x94, 0x51, 0x31, 0xb7,
	0xd7, 0x91, 0x5e, 0x7b, 0x7f, 0xbd, 0x00, 0x1d, 0xe7, 0x8c, 0xe7, 0x3e, 0x28, 0xf3, 0xa3, 0x5e,
	0xcd, 0x8f, 0x4f, 0x9a, 0x35, 0x8e, 0xb5, 0xb3, 0xe6, 0x33, 0xed, 0xec, 0x15, 0x58, 0xcb, 0xb9,
	0x0c, 0x0a, 0x73, 0xa5, 0x77, 0xa8, 0xa5, 0xc8, 0x0c, 0xea, 0x7b, 0x13, 0xeb, 0x95, 0xc7, 0xa7,
	0x13, 0xd7, 0xc1, 0x5e, 0xc6, 0x73, 0xa6, 0x44, 0x32, 0x9f, 0x2c, 0xa5, 0xe2, 0x31, 0xad, 0xef,
	0x4d, 0x70, 0xa0, 0x60, 0xd1, 0x21, 0x5b, 0x4a, 0xad, 0x5d, 0x5b, 0xeb, 0xd0, 0x35, 0x1c, 0x54,
	0xef, 0x8b, 0xb0, 0x85, 0x7d, 0xcf, 0x97, 0x41, 0x2e, 0x32, 0xa5, 0x6f, 0x74, 0x33, 0xa2, 0x6c,
	0x20, 0x7b, 0xa2, 0xb9, 0x78, 0xaf, 0xff, 0x10, 0x1a, 0x22, 0x93, 0xfd, 0xae, 0xbe, 0xcb, 0x46,
	0xa7, 0xa4, 0xef, 0x68, 0x4c, 0x11, 0x15, 0x9d, 0x5b, 0x48, 0x9e, 0xeb, 0x09, 0xd7, 0x8c, 0x3c,
	0x25, 0x4d, 0x76, 0xe0, 0x52, 0x90, 0x2f, 0x33, 0xc5, 0x43, 0x3f, 0x4f, 0x53, 0xe5, 0x67, 0x4c,
	0xca, 0xc3, 0x34, 0x0f, 0xf5, 0x10, 0xd4, 0xa5, 0x17, 0xec, 0x26, 0x4d, 0x53, 0x35, 0xb6, 0x5b,
	0x18, 0x73, 0xc5, 0xe6, 0xb2, 0xbf, 0xae, 0x47, 0x36, 0xbd, 0x26, 0x0b, 0x68, 0x4b, 0x95, 0xe6,
	0x6c, 0xce, 0xfb, 0x1b, 0xda, 0xe9, 0x0f, 0x4f, 0xc9, 0x88, 0x89, 0x41, 0xa5, 0x0e, 0x1e, 0xbb,
	0xa3, 0x94, 0x0b, 0x7f, 0x9f, 0x2f, 0x65, 0x7f, 0x53, 0x6b, 0xd0, 0x96, 0x72, 0xf1, 0x5d, 0xbe,
	0x94, 0xf8, 0x42, 0xb2, 0x23, 0xb2, 0x9f, 0x73, 0x16, 0x2e, 0xfb, 0x5b, 0x3a, 0x1e, 0xeb, 0x96,
	0x49, 0x91, 0xe7, 0xfd, 0xa6, 0x06, 0x5b, 0xcf, 0x44, 0xb2, 0xcc, 0xe2, 0xda, 0x51, 0x16, 0x63,
	0x66, 0x85, 0x42, 0xaa, 0x3c, 0x75, 0xad, 0xd6, 0x50, 0xd5, 0x61, 0xdb, 0xce, 0x66, 0x96, 0xc4,
	0x44, 0x15, 0x31, 0x9b, 0x73, 0x5f, 0xb1, 0xb9, 0x4e, 0xd4, 0x2e, 0xed, 0x68, 0xc6, 0x23, 0x36,
	0x27, 0x97, 0xa1, 0x9d, 0x4a, 0x5f, 0x4b, 0x69, 0x19, 0xbc, 0x54, 0x4e, 0xb0, 0x5a, 0xfe, 0x5c,
	0x7b, 0x79, 0x63, 0x22, 0xf2, 0xb3, 0x62, 0x1a, 0x89, 0xc0, 0x95, 0x8b, 0xa1, 0xc8, 0xe7, 0x00,
	0x62, 0x96, 0xb0, 0x39, 0x8f, 0x79, 0xa2, 0x74, 0xd9, 0x74, 0x68, 0x85, 0xe3, 0xfd, 0xab, 0x07,
	0x6d, 0x1b, 0x09, 0x9c, 0x20, 0x8f, 0xda, 0xa2, 0x90, 0xfb, 0xa8, 0x30, 0x86, 0xa1, 0x9c, 0x2e,
	0x86, 0xc8, 0x3c, 0xf6, 0x5c, 0xcd, 0x99, 0x08, 0xfb, 0x75, 0x7d, 0xaa, 0x9c, 0x19, 0x28, 0x13,
	0x21, 0xb9, 0x09, 0xe5, 0x9c, 0xe6, 0xcf, 0x44, 0xc4, 0xa5, 0x8e, 0x87, 0x69, 0xea, 0x5d, 0x7a,
	0xc1, 0xed, 0xdd, 0x3b, 0xda, 0x22, 0x02, 0x5a, 0x46, 0xaa, 0x79, 0x0d, 0x4e, 0x4e, 0x37, 0xcf,
	0x06, 0xa8, 0x3c, 0x35, 0x12, 0xc8, 0x1c, 0x9a, 0x5a, 0xf3, 0xd6, 0x99, 0x48, 0xa2, 0xb7, 0x46,
	0x43, 0xaa, 0x05, 0x90, 0x0f, 0xa0, 0x57, 0xb5, 0x7e, 0x4d, 0xcb, 0x7b, 0xf7, 0x94, 0xe5, 0x1d,
	0x39, 0x91, 0x56, 0xa5, 0x79, 0x7f, 0xab, 0x43, 0x13, 0xad, 0xd6, 0x19, 0xcf, 0x0f, 0x44, 0xe0,
	0x7a, 0xb7, 0xa5, 0xf0, 0x8e, 0x3b, 0x14, 0x19, 0xa6, 0xf5, 0x34, 0xe2, 0xf6, 0xb9, 0xd0, 0x45,
	0xce, 0x23, 0x64, 0x90, 0x0f, 0x01, 0x32, 0x96, 0x2b, 0xa1, 0x7f, 0xad, 0xd8, 0x71, 0xec, 0xc7,
	0x67, 0x10, 0x95, 0xc1, 0xd8, 0x49, 0xa1, 0x15, 0x81, 0xde, 0x2f, 0x6a, 0xd0, 0x2d, 0x77, 0xb0,
	0xbd, 0x44, 0x6c, 0xca, 0xdd, 0xe0, 0x6c, 0x08, 0xb4, 0x2c, 0x29, 0xe2, 0x29, 0xcf, 0xed, 0xe0,
	0x61, 0x29, 0x5d, 0xf7, 0xe2, 0x67, 0xa6, 0xe5, 0x34, 0xa8, 0x5e, 0xdb, 0x06, 0x95, 0x2b, 0x5b,
	0x39, 0x86, 0xc0, 0xda, 0x56, 0xcb, 0x8c, 0xfb, 0xf3, 0x42, 0xe7, 0x83, 0xae, 0x6d, 0x64, 0xdc,
	0x2f, 0x44, 0xe8, 0x25, 0xd0, 0x44, 0xe7, 0x22, 0x5c, 0xc6, 0xd4, 0xc2, 0x5d, 0x23, 0xb8, 0xfe,
	0xa4, 0x07, 0x00, 0x9e, 0xd7, 0xd3, 0x90, 0x15, 0x8f, 0x6b, 0xfd, 0x84, 0x10, 0xa1, 0x15, 0x8e,
	0x4b, 0xe4, 0xcc, 0xad, 0xd0, 0x06, 0xc5, 0xa5, 0xf7, 0x9f, 0x3a, 0xb4, 0x76, 0xd3, 0x22, 0x51,
	0xff, 0x37, 0x64, 0x58, 0xff, 0x69, 0x1e, 0x33, 0xe5, 0x2e, 0x2f, 0x43, 0x61, 0xf1, 0xe8, 0xd0,
	0xdb, 0x30, 0x4d, 0xce, 0x20, 0xc5, 0xa8, 0x91, 0x40, 0x3e, 0x82, 0xb5, 0x20, 0xe7, 0xd8, 0xe9,
	0xcd, 0x74, 0x35, 0x3b, 0x65, 0x59, 0xda, 0x01, 0x95, 0xa4, 0xde, 0xcb, 0x74, 0x3e, 0x50, 0x2b,
	0x15, 0xe3, 0x98, 0xa5, 0x22, 0x51, 0x36, 0x5a, 0x86, 0xf0, 0xee, 0xc0, 0xf9, 0xe7, 0x3e, 0xc1,
	0xa3, 0xb3, 0x34, 0x0f, 0xdc, 0x63, 0xd9, 0x10, 0x78, 0xbb, 0xa6, 0xe6, 0x80, 0xbd, 0xba, 0x1c,
	0xe9, 0x3d, 0x05, 0x38, 0x02, 0x21, 0xef, 0x41, 0x2b, 0x46, 0x5d, 0xec, 0x98, 0xfe, 0xe8, 0x2c,
	0xec, 0xa4, 0x46, 0x84, 0xf7, 0x53, 0x68, 0xe2, 0xb5, 0x81, 0x99, 0xa3, 0x67, 0x25, 0x9b, 0x69,
	0x7a, 0x4e, 0xc2, 0xd4, 0xe7, 0x07, 0xe5, 0xd3, 0xd0, 0x10, 0x68, 0x85, 0xc9, 0x09, 0x77, 0xa9,
	0x3a, 0x52, 0x27, 0x7a, 0xc6, 0x72, 0x5e, 0x26, 0x3a, 0x12, 0xf8, 0x02, 0x59, 0x33, 0x73, 0x26,
	0xf9, 0x39, 0x6c, 0x65, 0x39, 0xd7, 0xc3, 0x6c, 0x14, 0xf1, 0xd0, 0x4f, 0xa5, 0x35, 0xf1, 0xac,
	0x06, 0xaa, 0xcd, 0xaa, 0xb8, 0x3d, 0x49, 0xbe, 0x84, 0x0a, 0x88, 0x03, 0xa6, 0xb8, 0x2f, 0x8b,
	0x69, 0xc2, 0x95, 0x8b, 0xc4, 0xa6, 0x65, 0x4f, 0x0c, 0xd7, 0x7b, 0x0a, 0x1d, 0x37, 0xbb, 0x62,
	0xa5, 0x66, 0x11, 0x4b, 0xfc, 0x4a, 0x43, 0xef, 0x20, 0x03, 0x9b, 0x2d, 0xb9, 0x0e, 0xe7, 0xf5,
	0xa6, 0x6d, 0xd9, 0x7e, 0x65, 0x76, 0xdd, 0xc2, 0x8d, 0xc7, 0x86, 0xaf, 0xcf, 0xbe, 0x0e, 0x1b,
	0x6e, 0x0c, 0xf6, 0x03, 0x57, 0xa6, 0x5d, 0xba, 0xee, 0x98, 0x77, 0xd2, 0x90, 0x6f, 0xbf, 0x06,
	0x1b, 0x43, 0x1e, 0x71, 0xc5, 0xdd, 0x4f, 0xde, 0x4d, 0xa8, 0x8f, 0x86, 0x6e, 0xde, 0x1d, 0x0d,
	0x77, 0x3e, 0x6e, 0xc3, 0x96, 0x73, 0xc1, 0x84, 0xe7, 0xba, 0x3a, 0x7f, 0x5d, 0x83, 0xe6, 0xb8,
	0x90, 0x0b, 0xf2, 0xf5, 0x17, 0x71, 0x64, 0xe5, 0x5f, 0xb5, 0x77, 0xf3, 0x45, 0x3e, 0x34, 0xff,
	0xa2, 0x2f, 0xff, 0xf2, 0xe3, 0x7f, 0xfc, 0xa1, 0x7e, 0x7e, 0x7b, 0xfd, 0xc6, 0xc1, 0xcd, 0xf2,
	0x9f, 0xfa, 0x37, 0x6b, 0xd7, 0xc9, 0xef, 0x6b, 0xd0, 0xba, 0xbd, 0xdc, 0xbd, 0x75, 0x87, 0x7c,
	0xed, 0x45, 0x50, 0x8f, 0x7e, 0x6c, 0x7b, 0x27, 0xfa, 0x57, 0xbe, 0xfd, 0xaa, 0x56, 0xe8, 0xd2,
	0xf6, 0xb9, 0xaa, 0x42, 0x37, 0x62, 0x16, 0xa0, 0x52, 0xbf, 0xab, 0x41, 0xf3, 0xf6, 0x72, 0x34,
	0x7e, 0xc9, 0x3a, 0x79, 0x5a, 0xa7, 0x8b, 0xdb, 0x5b, 0xc7, 0x74, 0x12, 0x19, 0xaa, 0xf4, 0x5b,
	0xa3, 0xd2, 0xf0, 0x25, 0xab, 0x74, 0x45, 0xab, 0x74, 0x81, 0x9c, 0x3f, 0xa6, 0xd2, 0x07, 0x22,
	0xfc, 0x90, 0xfc, 0xaa, 0x06, 0x8d, 0x5b, 0x51, 0x44, 0x5e, 0x3c, 0x1b, 0x4e, 0xa8, 0xcb, 0x45,
	0xad, 0xcb, 0x26, 0x39, 0x96, 0x43, 0x6f, 0xd4, 0xc8, 0x21, 0xb4, 0x9e, 0x30, 0x15, 0x2c, 0x5e,
	0xae, 0x6b, 0xde, 0xa8, 0x91, 0x03, 0x58, 0x33, 0xe5, 0x47, 0x5e, 0xe8, 0xef, 0xc8, 0xb1, 0x92,
	0x3d, 0x41, 0x31, 0xdd, 0x86, 0x1f, 0x74, 0x1c, 0x67, 0xba, 0xa6, 0x8f, 0x7c, 0xf5, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x18, 0x61, 0xf3, 0x5a, 0xb2, 0x1a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HardwareServiceClient is the client API for HardwareService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HardwareServiceClient interface {
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*Empty, error)
	ByMAC(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Hardware, error)
	ByIP(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Hardware, error)
	ByID(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Hardware, error)
	All(ctx context.Context, in *Empty, opts ...grpc.CallOption) (HardwareService_AllClient, error)
	Watch(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (HardwareService_WatchClient, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error)
}

type hardwareServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHardwareServiceClient(cc grpc.ClientConnInterface) HardwareServiceClient {
	return &hardwareServiceClient{cc}
}

func (c *hardwareServiceClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/github.com.tinkerbell.tink.protos.hardware.HardwareService/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hardwareServiceClient) ByMAC(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Hardware, error) {
	out := new(Hardware)
	err := c.cc.Invoke(ctx, "/github.com.tinkerbell.tink.protos.hardware.HardwareService/ByMAC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hardwareServiceClient) ByIP(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Hardware, error) {
	out := new(Hardware)
	err := c.cc.Invoke(ctx, "/github.com.tinkerbell.tink.protos.hardware.HardwareService/ByIP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hardwareServiceClient) ByID(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Hardware, error) {
	out := new(Hardware)
	err := c.cc.Invoke(ctx, "/github.com.tinkerbell.tink.protos.hardware.HardwareService/ByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hardwareServiceClient) All(ctx context.Context, in *Empty, opts ...grpc.CallOption) (HardwareService_AllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HardwareService_serviceDesc.Streams[0], "/github.com.tinkerbell.tink.protos.hardware.HardwareService/All", opts...)
	if err != nil {
		return nil, err
	}
	x := &hardwareServiceAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HardwareService_AllClient interface {
	Recv() (*Hardware, error)
	grpc.ClientStream
}

type hardwareServiceAllClient struct {
	grpc.ClientStream
}

func (x *hardwareServiceAllClient) Recv() (*Hardware, error) {
	m := new(Hardware)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hardwareServiceClient) Watch(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (HardwareService_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HardwareService_serviceDesc.Streams[1], "/github.com.tinkerbell.tink.protos.hardware.HardwareService/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &hardwareServiceWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HardwareService_WatchClient interface {
	Recv() (*Hardware, error)
	grpc.ClientStream
}

type hardwareServiceWatchClient struct {
	grpc.ClientStream
}

func (x *hardwareServiceWatchClient) Recv() (*Hardware, error) {
	m := new(Hardware)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hardwareServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/github.com.tinkerbell.tink.protos.hardware.HardwareService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HardwareServiceServer is the server API for HardwareService service.
type HardwareServiceServer interface {
	Push(context.Context, *PushRequest) (*Empty, error)
	ByMAC(context.Context, *GetRequest) (*Hardware, error)
	ByIP(context.Context, *GetRequest) (*Hardware, error)
	ByID(context.Context, *GetRequest) (*Hardware, error)
	All(*Empty, HardwareService_AllServer) error
	Watch(*GetRequest, HardwareService_WatchServer) error
	Delete(context.Context, *DeleteRequest) (*Empty, error)
}

// UnimplementedHardwareServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHardwareServiceServer struct {
}

func (*UnimplementedHardwareServiceServer) Push(ctx context.Context, req *PushRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (*UnimplementedHardwareServiceServer) ByMAC(ctx context.Context, req *GetRequest) (*Hardware, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ByMAC not implemented")
}
func (*UnimplementedHardwareServiceServer) ByIP(ctx context.Context, req *GetRequest) (*Hardware, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ByIP not implemented")
}
func (*UnimplementedHardwareServiceServer) ByID(ctx context.Context, req *GetRequest) (*Hardware, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ByID not implemented")
}
func (*UnimplementedHardwareServiceServer) All(req *Empty, srv HardwareService_AllServer) error {
	return status.Errorf(codes.Unimplemented, "method All not implemented")
}
func (*UnimplementedHardwareServiceServer) Watch(req *GetRequest, srv HardwareService_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (*UnimplementedHardwareServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterHardwareServiceServer(s *grpc.Server, srv HardwareServiceServer) {
	s.RegisterService(&_HardwareService_serviceDesc, srv)
}

func _HardwareService_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareServiceServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.tinkerbell.tink.protos.hardware.HardwareService/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareServiceServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HardwareService_ByMAC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareServiceServer).ByMAC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.tinkerbell.tink.protos.hardware.HardwareService/ByMAC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareServiceServer).ByMAC(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HardwareService_ByIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareServiceServer).ByIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.tinkerbell.tink.protos.hardware.HardwareService/ByIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareServiceServer).ByIP(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HardwareService_ByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareServiceServer).ByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.tinkerbell.tink.protos.hardware.HardwareService/ByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareServiceServer).ByID(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HardwareService_All_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HardwareServiceServer).All(m, &hardwareServiceAllServer{stream})
}

type HardwareService_AllServer interface {
	Send(*Hardware) error
	grpc.ServerStream
}

type hardwareServiceAllServer struct {
	grpc.ServerStream
}

func (x *hardwareServiceAllServer) Send(m *Hardware) error {
	return x.ServerStream.SendMsg(m)
}

func _HardwareService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HardwareServiceServer).Watch(m, &hardwareServiceWatchServer{stream})
}

type HardwareService_WatchServer interface {
	Send(*Hardware) error
	grpc.ServerStream
}

type hardwareServiceWatchServer struct {
	grpc.ServerStream
}

func (x *hardwareServiceWatchServer) Send(m *Hardware) error {
	return x.ServerStream.SendMsg(m)
}

func _HardwareService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HardwareServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.tinkerbell.tink.protos.hardware.HardwareService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HardwareServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HardwareService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.tinkerbell.tink.protos.hardware.HardwareService",
	HandlerType: (*HardwareServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _HardwareService_Push_Handler,
		},
		{
			MethodName: "ByMAC",
			Handler:    _HardwareService_ByMAC_Handler,
		},
		{
			MethodName: "ByIP",
			Handler:    _HardwareService_ByIP_Handler,
		},
		{
			MethodName: "ByID",
			Handler:    _HardwareService_ByID_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _HardwareService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "All",
			Handler:       _HardwareService_All_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _HardwareService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hardware/hardware.proto",
}
