name: ESS-Devops
on:
  push:

jobs:
  build:
    runs-on: metal
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'
    - name: set GOCACHE
      run: |
        echo "GOCACHE=$PWD/.cache" >> $GITHUB_ENV
        mkdir $PWD/.cache
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'
    - name: get ENV
      run: printenv
    - name: Compile tink-cli
      run: go build -o ./cmd/tink-cli ./cmd/tink-cli
    - name: Build tink-cli
      run: docker build cmd/tink-cli -t quay.io/ess_metal/tink-cli:$GITHUB_RUN_NUMBER
