name: ESS-Devops
on:
  push:

jobs:
  build:
    runs-on: metal
    steps:
    - name: Env
      run: echo "::set-env name=PATH::/usr/local/go/bin"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set GOPATH
      run: echo "/usr/local/go/bin" >> $GITHUB_PATH
    - name: Compile tink-cli
      run: go build -o ./cmd/tink-cli ./cmd/tink-cli
    - name: Build tink-cli
      run: docker build cmd/tink-cli -t quay.io/ess_metal/tink-cli:$GITHUB_RUN_NUMBER
