name: ESS-Devops
on:
  push:

jobs:
  build:
    runs-on: metal
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: set GOPATH
      run: echo "/usr/local/go/bin" >> $GITHUB_PATH
    - name: set GOCACHE
      run: echo "GOCACHE=.cache" >> $GITHUB_ENV
    - name: get ENV
      run: printenv
    - name: Compile tink-cli
      run: go build -o ./cmd/tink-cli ./cmd/tink-cli
    - name: Build tink-cli
      run: docker build cmd/tink-cli -t quay.io/ess_metal/tink-cli:$GITHUB_RUN_NUMBER
