name: ESS-Devops
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: set Go dir
      run: mkdir -p $HOME/work/tink/go
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/packethost/tink
    - name: Set Env
      run: echo "GOPATH=$HOME/work/tink/go" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: get ENV
      run: printenv
    - name: Compile tink-cli
      run: go build -o ./cmd/tink-cli ./cmd/tink-cli
    - name: Get the version
      id: get_version
      run: |
        echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
        echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV
    - name: Set version
      if: ${{ steps.get_version.outputs.VERSION == '' }}
      run: echo "VERSION=sha-${GITHUB_SHA::8}" >> $GITHUB_ENV
    - name: Build tink-cli
      run: docker build cmd/tink-cli -t quay.io/ess_metal/tink-cli:$VERSION
